---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pixelated-ingress
  namespace: pixelated
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: pixelatedempathy.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pixelated-service
                port:
                  number: 80
    - host: www.pixelatedempathy.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pixelated-service
                port:
                  number: 80