apiVersion: v1
kind: Service
metadata:
  labels:
    app: pixelated-app
  name: pixelated-service
  namespace: pixelated
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 4321
  selector:
    app: pixelated-app
  type: LoadBalancer
