---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pixelated-config
  namespace: pixelated
data:
  app.json: |
    {
      "name": "pixelated",
      "version": "1.0.0",
      "environment": "production",
      "features": {
        "ai_chat": true,
        "user_registration": true,
        "analytics": true
      }
    }