# Checkov Configuration
# This file configures Checkov scanning rules and exclusions

policy-metadata-filter:
  # Exclude false positive secret detections in Helm values
  exclude:
    - CKV_SECRET_6

# Skip specific checks for known false positives
skip-check:
  # Helm values.yaml contains configuration keys and comments, not actual secrets
  - CKV_SECRET_6:helm/values.yaml

# Framework-specific configurations
framework:
  - terraform
  - secrets
  - bicep
  - azure_pipelines

# Output format for CI/CD integration
output:
  - cli
  - sarif
  - json

# Custom policies directory (if any)
# policy-path: .checkov

# External checks
# external-checks-dir:
#   - custom_checks

# Performance optimizations
compact: true
quiet: false

# Baseline file for incremental scanning
# baseline: security-baseline.json

# Enable soft fail for CI/CD environments
soft-fail: false

# Download external modules for Terraform
download-external-modules: false

# Secrets scanning configuration
skip-path:
  # Disable secrets scanning for Helm values files as they contain configuration
  - helm/values.yaml

# Azure Pipelines specific configuration removed - not a valid Checkov config section
