services:
  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      frontend:
        condition: service_healthy
      bias-detection-service:
        condition: service_healthy
    restart: always

  bias-detection-service:
    build:
      context: ./src/lib/ai/bias-detection
      dockerfile: Dockerfile
    environment:
      BIAS_SERVICE_HOST: 0.0.0.0
      BIAS_SERVICE_PORT: 5001
      GUNICORN_WORKERS: 4
      GUNICORN_WORKER_CLASS: gevent
      GUNICORN_TIMEOUT: 120
      GUNICORN_LOGLEVEL: info
      GUNICORN_DAEMON: "false"
      GUNICORN_PRELOAD_APP: "false"
    restart: always
    volumes:
      - ./src/lib/ai/bias-detection:/app
    healthcheck:
      test: ["CMD", "/app/check_service_health.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pixelated-empathy
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 4321
      NEXT_PUBLIC_BIAS_API_URL: http://nginx/api/bias-detection
    depends_on:
      bias-detection-service:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4321/api/health/simple"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s