version: '3.8'

services:
  pixelated-app-new:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pixelated-app-new
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  