---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-agent
  namespace: flux-system
spec:
  chart:
    spec:
      chart: gitlab-agent
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: gitlab-agent
  targetNamespace: gitlab-agent
  values:
    config:
      kasAddress: wss://kas.gitlab.com
      secretName: gitlab-agent-token
