apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixelated
  labels:
    app: pixelated
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pixelated
  template:
    metadata:
      labels:
        app: pixelated
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      securityContext:
        runAsUser: 10001
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: pixelated
        image: registry.gitlab.com/pixeldeck/pixelated:latest
        ports:
        - containerPort: 4321
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "4321"
        - name: PUBLIC_CLERK_PUBLISHABLE_KEY
          value: "pk_test_ZXhwZXJ0LWNvdWdhci0yNi5jbGVyay5hY2NvdW50cy5kZXYk"
        - name: CLERK_SECRET_KEY
          value: "sk_test_your_secret_key_here"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        livenessProbe:
          httpGet:
            path: /
            port: 4321
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 4321
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pixelated-service
spec:
  selector:
    app: pixelated
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4321
  type: LoadBalancer
