services:
  evaluator:
    image: ${NEMO_MICROSERVICES_IMAGE_REGISTRY}/evaluator:${NEMO_MICROSERVICES_IMAGE_TAG}
    profiles: [evaluator, platform]
    ports:
      - 7331
    depends_on:
      datastore:
        condition: service_started
      postgres:
        condition: service_healthy
      evaluator-postgres-db-migration:
        condition: service_completed_successfully
      evaluator-internal:
        condition: service_started
      jobs-api:
        condition: service_healthy
      jobs-controller:
        condition: service_started
    networks:
      - nmp
    healthcheck:
      test: [
        "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7331/health"
      ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 20s
    environment:
      MODE: standalone
      POSTGRES_URI: postgresql://nmp:nmp@postgres:5432/evaluator
      DATA_STORE_URL: http://datastore:3000/v1/hf
      EVALUATIONS_CALLBACK_URL: http://evaluator-internal:7332
      NEMO_MICROSERVICES_JOBS_URL: http://jobs-api:8000
      NEMO_MICROSERVICES_DATASTORE_URL: http://datastore:3000/v1/hf # /results endpoint
      EVALUATOR_IMAGE: ${NEMO_MICROSERVICES_IMAGE_REGISTRY}/evaluator:${NEMO_MICROSERVICES_IMAGE_TAG}
    entrypoint: ["python", "-m", "evaluator.server"]


  evaluator-internal:
    image: ${NEMO_MICROSERVICES_IMAGE_REGISTRY}/evaluator:${NEMO_MICROSERVICES_IMAGE_TAG}
    profiles: [evaluator, platform]
    ports:
      - 7332
    depends_on:
      postgres:
        condition: service_healthy
      evaluator-postgres-db-migration:
        condition: service_completed_successfully
    networks:
      - nmp
    healthcheck:
      test: [
        "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7332/health"
      ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s
    environment:
      MODE: standalone
      POSTGRES_URI: postgresql://nmp:nmp@postgres:5432/evaluator
      EVALUATOR_PORT_INTERNAL: 7332
    entrypoint: ["python", "-m", "evaluator.internal_server"]


  evaluator-postgres-db-migration:
    image: ${NEMO_MICROSERVICES_IMAGE_REGISTRY}/evaluator:${NEMO_MICROSERVICES_IMAGE_TAG}
    profiles: [evaluator, platform]
    environment:
      MODE: standalone
      POSTGRES_URI: "postgresql://nmp:nmp@postgres:5432/evaluator"
      DATA_STORE_URL: none
    entrypoint: /bin/sh
    command: ["-c", "/app/scripts/run-db-migration.sh"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nmp
