groups:
  - name: pixelated_empathy_ai_alerts
    rules:
      # High CPU usage
      - alert: HighCPUUsage
        expr: cpu_usage_percent > 80
        for: 5m
        labels:
          severity: warning
          service: pixelated-empathy-ai
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value }}% for more than 5 minutes"

      # Critical CPU usage
      - alert: CriticalCPUUsage
        expr: cpu_usage_percent > 95
        for: 2m
        labels:
          severity: critical
          service: pixelated-empathy-ai
        annotations:
          summary: "Critical CPU usage detected"
          description: "CPU usage is {{ $value }}% for more than 2 minutes"

      # High memory usage
      - alert: HighMemoryUsage
        expr: memory_usage_bytes / (1024*1024*1024) > 3
        for: 5m
        labels:
          severity: warning
          service: pixelated-empathy-ai
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value }}GB for more than 5 minutes"

      # Critical memory usage
      - alert: CriticalMemoryUsage
        expr: memory_usage_bytes / (1024*1024*1024) > 7
        for: 2m
        labels:
          severity: critical
          service: pixelated-empathy-ai
        annotations:
          summary: "Critical memory usage detected"
          description: "Memory usage is {{ $value }}GB for more than 2 minutes"

      # High disk usage
      - alert: HighDiskUsage
        expr: disk_usage_percent > 85
        for: 10m
        labels:
          severity: warning
          service: pixelated-empathy-ai
        annotations:
          summary: "High disk usage detected"
          description: "Disk usage on {{ $labels.mount }} is {{ $value }}% for more than 10 minutes"

      # Critical disk usage
      - alert: CriticalDiskUsage
        expr: disk_usage_percent > 95
        for: 5m
        labels:
          severity: critical
          service: pixelated-empathy-ai
        annotations:
          summary: "Critical disk usage detected"
          description: "Disk usage on {{ $labels.mount }} is {{ $value }}% for more than 5 minutes"

      # Application down
      - alert: ApplicationDown
        expr: up{job="pixelated-empathy-ai"} == 0
        for: 1m
        labels:
          severity: critical
          service: pixelated-empathy-ai
        annotations:
          summary: "Pixelated Empathy AI application is down"
          description: "The application has been down for more than 1 minute"

      # High HTTP error rate
      - alert: HighHTTPErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: pixelated-empathy-ai
        annotations:
          summary: "High HTTP error rate detected"
          description: "HTTP error rate is {{ $value | humanizePercentage }} for more than 5 minutes"

      # High response time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          service: pixelated-empathy-ai
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s for more than 5 minutes"

      # Database connection issues
      - alert: DatabaseConnectionIssues
        expr: database_connections{state="active"} < 1
        for: 2m
        labels:
          severity: critical
          service: pixelated-empathy-ai
        annotations:
          summary: "Database connection issues detected"
          description: "No active database connections for more than 2 minutes"

      # High AI inference latency
      - alert: HighAIInferenceLatency
        expr: histogram_quantile(0.95, rate(ai_inference_duration_seconds_bucket[5m])) > 10
        for: 5m
        labels:
          severity: warning
          service: pixelated-empathy-ai
        annotations:
          summary: "High AI inference latency detected"
          description: "95th percentile AI inference time is {{ $value }}s for more than 5 minutes"

      # AI inference failures
      - alert: AIInferenceFailures
        expr: rate(ai_inference_total{status="error"}[5m]) > 0.05
        for: 3m
        labels:
          severity: warning
          service: pixelated-empathy-ai
        annotations:
          summary: "AI inference failures detected"
          description: "AI inference error rate is {{ $value | humanizePercentage }} for more than 3 minutes"

      # Low cache hit rate
      - alert: LowCacheHitRate
        expr: rate(cache_hits_total[5m]) / (rate(cache_hits_total[5m]) + rate(cache_misses_total[5m])) < 0.8
        for: 10m
        labels:
          severity: warning
          service: pixelated-empathy-ai
        annotations:
          summary: "Low cache hit rate detected"
          description: "Cache hit rate is {{ $value | humanizePercentage }} for more than 10 minutes"

  - name: infrastructure_alerts
    rules:
      # Node down
      - alert: NodeDown
        expr: up{job="node-exporter"} == 0
        for: 2m
        labels:
          severity: critical
          service: infrastructure
        annotations:
          summary: "Node is down"
          description: "Node {{ $labels.instance }} has been down for more than 2 minutes"

      # PostgreSQL down
      - alert: PostgreSQLDown
        expr: up{job="postgres-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          service: database
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database has been down for more than 1 minute"

      # Redis down
      - alert: RedisDown
        expr: up{job="redis-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          service: cache
        annotations:
          summary: "Redis is down"
          description: "Redis cache has been down for more than 1 minute"

      # High network traffic
      - alert: HighNetworkTraffic
        expr: rate(node_network_receive_bytes_total[5m]) > 100*1024*1024
        for: 10m
        labels:
          severity: warning
          service: infrastructure
        annotations:
          summary: "High network traffic detected"
          description: "Network receive traffic is {{ $value | humanize }}B/s for more than 10 minutes"

  - name: kubernetes_alerts
    rules:
      # Pod crash looping
      - alert: PodCrashLooping
        expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
        for: 5m
        labels:
          severity: warning
          service: kubernetes
        annotations:
          summary: "Pod is crash looping"
          description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is crash looping"

      # Pod not ready
      - alert: PodNotReady
        expr: kube_pod_status_ready{condition="false"} == 1
        for: 5m
        labels:
          severity: warning
          service: kubernetes
        annotations:
          summary: "Pod is not ready"
          description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has been not ready for more than 5 minutes"

      # Deployment replica mismatch
      - alert: DeploymentReplicaMismatch
        expr: kube_deployment_spec_replicas != kube_deployment_status_available_replicas
        for: 5m
        labels:
          severity: warning
          service: kubernetes
        annotations:
          summary: "Deployment replica mismatch"
          description: "Deployment {{ $labels.namespace }}/{{ $labels.deployment }} has {{ $labels.spec_replicas }} desired but {{ $labels.available_replicas }} available replicas"
