version: '3.8'

services:
  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager_data:/alertmanager
    networks:
      - pixelated-network
    restart: unless-stopped

volumes:
  alertmanager_data:

networks:
  pixelated-network:
    driver: bridge