# Production Security Configuration for Pixelated Empathy AI

# Master encryption settings
encryption:
  master_key: ${MASTER_ENCRYPTION_KEY}
  algorithm: AES-256-GCM
  key_rotation_days: 90
  backup_keys: 3

# Authentication settings
authentication:
  jwt_secret: ${JWT_SECRET}
  jwt_expiry_hours: 24
  refresh_token_expiry_days: 30
  
  # Password policy
  password_policy:
    min_length: 12
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_symbols: true
    expiry_days: 90
    history_count: 12  # Remember last 12 passwords
    
  # Account lockout policy
  lockout_policy:
    max_attempts: 5
    lockout_duration_minutes: 60
    progressive_delay: true  # Increase delay with each attempt
    
  # Multi-factor authentication
  mfa:
    required_roles: ["admin", "security", "clinician"]
    backup_codes: 10
    totp_window: 30  # seconds
    recovery_codes: true

# Authorization settings
authorization:
  # Role-based access control
  rbac:
    enabled: true
    default_role: "user"
    role_hierarchy:
      - "user"
      - "clinician"
      - "supervisor"
      - "admin"
      - "security"
    
  # Security levels
  security_levels:
    public: 0
    internal: 1
    confidential: 2
    restricted: 3
    top_secret: 4
    
  # Resource permissions
  permissions:
    user_data:
      read: ["user", "clinician", "supervisor", "admin"]
      write: ["clinician", "supervisor", "admin"]
      delete: ["supervisor", "admin"]
    
    system_config:
      read: ["admin", "security"]
      write: ["admin"]
      delete: ["admin"]
    
    audit_logs:
      read: ["security", "admin"]
      write: ["security"]
      delete: []  # Never allow deletion

# Network security
network:
  # IP whitelisting
  ip_whitelist:
    enabled: true
    allowed_ranges:
      - "10.0.0.0/8"      # Internal network
      - "172.16.0.0/12"   # Private network
      - "192.168.0.0/16"  # Local network
    
  # Rate limiting
  rate_limiting:
    enabled: true
    requests_per_hour: 1000
    burst_limit: 100
    
    # Per-endpoint limits
    endpoints:
      "/api/auth/login":
        requests_per_hour: 10
        burst_limit: 3
      "/api/chat":
        requests_per_hour: 100
        burst_limit: 20
      "/api/admin":
        requests_per_hour: 50
        burst_limit: 10
  
  # DDoS protection
  ddos_protection:
    enabled: true
    threshold_requests_per_second: 100
    block_duration_minutes: 15
    
  # SSL/TLS settings
  tls:
    min_version: "1.2"
    cipher_suites:
      - "ECDHE-RSA-AES256-GCM-SHA384"
      - "ECDHE-RSA-AES128-GCM-SHA256"
      - "ECDHE-RSA-AES256-SHA384"
    hsts_max_age: 31536000  # 1 year
    certificate_transparency: true

# Data protection
data_protection:
  # Encryption at rest
  encryption_at_rest:
    enabled: true
    algorithm: "AES-256-GCM"
    key_management: "aws-kms"  # or "vault", "local"
    
  # Encryption in transit
  encryption_in_transit:
    enabled: true
    force_https: true
    certificate_pinning: true
    
  # Data classification
  classification:
    pii_fields:
      - "email"
      - "phone"
      - "address"
      - "ssn"
    
    sensitive_fields:
      - "password"
      - "api_key"
      - "session_token"
      - "medical_data"
    
    public_fields:
      - "username"
      - "created_at"
      - "last_login"

# Audit and compliance
audit:
  # Logging settings
  logging:
    enabled: true
    level: "INFO"
    retention_days: 2555  # 7 years for compliance
    
    # Log categories
    categories:
      authentication: true
      authorization: true
      data_access: true
      configuration_changes: true
      security_events: true
      admin_actions: true
    
    # Log destinations
    destinations:
      file: "/var/log/security/audit.log"
      syslog: "localhost:514"
      elasticsearch: "${ELASTICSEARCH_URL}"
      s3: "${S3_AUDIT_BUCKET}"
  
  # Compliance frameworks
  compliance:
    hipaa:
      enabled: true
      encryption_required: true
      audit_trail_required: true
      access_controls_required: true
    
    gdpr:
      enabled: true
      data_retention_days: 2555
      right_to_erasure: true
      consent_tracking: true
    
    sox:
      enabled: false
      financial_controls: false

# Threat detection
threat_detection:
  # Anomaly detection
  anomaly_detection:
    enabled: true
    baseline_days: 30
    sensitivity: "medium"  # low, medium, high
    
    # Behavioral analysis
    behavioral_analysis:
      login_patterns: true
      access_patterns: true
      geographic_analysis: true
      time_based_analysis: true
  
  # Intrusion detection
  intrusion_detection:
    enabled: true
    
    # Attack patterns
    patterns:
      sql_injection: true
      xss_attacks: true
      brute_force: true
      privilege_escalation: true
      data_exfiltration: true
    
    # Response actions
    response:
      auto_block: true
      alert_security_team: true
      quarantine_session: true

# Security monitoring
monitoring:
  # Real-time monitoring
  real_time:
    enabled: true
    dashboard_url: "${SECURITY_DASHBOARD_URL}"
    
    # Metrics to track
    metrics:
      - "failed_login_attempts"
      - "privilege_escalations"
      - "data_access_violations"
      - "suspicious_activities"
      - "threat_scores"
    
  # Alerting
  alerting:
    enabled: true
    
    # Alert channels
    channels:
      email:
        enabled: true
        recipients: ["security@pixelated-empathy.ai"]
        severity_threshold: "medium"
      
      slack:
        enabled: true
        webhook_url: "${SLACK_SECURITY_WEBHOOK}"
        channel: "#security-alerts"
        severity_threshold: "high"
      
      pagerduty:
        enabled: true
        service_key: "${PAGERDUTY_SERVICE_KEY}"
        severity_threshold: "critical"
    
    # Alert rules
    rules:
      - name: "Multiple Failed Logins"
        condition: "failed_login_attempts > 10 in 5 minutes"
        severity: "high"
        
      - name: "Privilege Escalation Attempt"
        condition: "privilege_escalation_detected"
        severity: "critical"
        
      - name: "Unusual Data Access"
        condition: "data_access_anomaly_score > 0.8"
        severity: "medium"

# Incident response
incident_response:
  # Automated responses
  automated_response:
    enabled: true
    
    # Response actions
    actions:
      block_ip:
        enabled: true
        duration_minutes: 60
        
      disable_account:
        enabled: true
        requires_approval: true
        
      quarantine_session:
        enabled: true
        immediate: true
  
  # Manual response procedures
  procedures:
    security_breach:
      - "Isolate affected systems"
      - "Preserve evidence"
      - "Notify security team"
      - "Begin forensic analysis"
      - "Communicate with stakeholders"
    
    data_breach:
      - "Assess scope of breach"
      - "Contain the breach"
      - "Notify authorities (72 hours)"
      - "Notify affected users"
      - "Implement remediation"

# Security testing
security_testing:
  # Penetration testing
  penetration_testing:
    frequency: "quarterly"
    scope: "full_application"
    external_vendor: true
    
  # Vulnerability scanning
  vulnerability_scanning:
    frequency: "weekly"
    tools: ["nessus", "openvas", "qualys"]
    auto_remediation: false
    
  # Security code review
  code_review:
    enabled: true
    automated_tools: ["sonarqube", "checkmarx"]
    manual_review_required: true
    
  # Security training
  training:
    frequency: "annual"
    mandatory: true
    topics:
      - "Secure coding practices"
      - "Threat awareness"
      - "Incident response"
      - "Compliance requirements"
