---
# Namespace-scoped Role for Flux to access secrets in flux-system namespace only
# This replaces the cluster-wide secret access with namespace-scoped access (KSV041 fix)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flux-secret-reader
  namespace: flux-system
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v2.6.4
rules:
- apiGroups: [ "" ]
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-secret-reader
  namespace: flux-system
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v2.6.4
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flux-secret-reader
subjects:
- kind: ServiceAccount
  name: source-controller
  namespace: flux-system
- kind: ServiceAccount
  name: kustomize-controller
  namespace: flux-system
- kind: ServiceAccount
  name: helm-controller
  namespace: flux-system
- kind: ServiceAccount
  name: notification-controller
  namespace: flux-system
