---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-controller-flux-system
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v2.6.4
rules:
  - apiGroups: [source.toolkit.fluxcd.io]
    resources: [gitrepositories, buckets, helmrepositories, ocirepositories]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [kustomize.toolkit.fluxcd.io]
    resources: [kustomizations]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [helm.toolkit.fluxcd.io]
    resources: [helmreleases]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [notification.toolkit.fluxcd.io]
    resources: [alerts, providers, receivers]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [image.toolkit.fluxcd.io]
    resources:
      [
        imagerepositories,
        imagereflectors,
        imagepolicies,
        imageupdateautomations,
      ]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [""]
    resources:
      - namespaces
      - configmaps
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups: [""]
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: [""]
    resources:
      - configmaps/status
    verbs:
      - get
      - update
      - patch
  - apiGroups: [coordination.k8s.io]
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: [""]
    resources:
      - serviceaccounts/token
    verbs:
      - create
  - nonResourceURLs:
      - /livez/ping
    verbs:
      - head
