---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: pixelated-empathy
  namespace: flux-system
spec:
  image: docker.io/pixelatedempathy/pixelated-empathy
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: pixelated-empathy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: pixelated-empathy
  filterTags:
    pattern: ^build-(?P<ts>\d+)$
    extract: $ts
  policy:
    numerical:
      order: asc
---
apiVersion: automation.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: pixelated-empathy
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        chore(image-automation): update pixelated-empathy to {{range .Updated.Images}}{{.NewTag}}{{end}}
    push:
      branch: master
  update:
    path: ./clusters/pixelkube/pixelated
    strategy: Setters

