configs:

  local_config:
    content: |
      models: []

  local_default_config:
    content: |
      models:
        - type: main
          engine: nim
          parameters:
            base_url: "http://llama-3-3-70b-instruct:8000"
            model_name: llama-3.3-70b-instruct

        - type: content_safety
          engine: nim
          parameters:
            base_url: "http://nim-content-safety:8000"
            model_name: llama-3.1-nemoguard-8b-content-safety

        - type: topic_control
          engine: nim
          parameters:
            base_url: "http://nim-topic-control:8000"
            model_name: llama-3.1-nemoguard-8b-topic-control


  local_quickstart_config:
    content: |
      models:
        - type: main
          engine: nim
          parameters:
            base_url: "http://llama-3-3-70b-instruct:8000"
            model_name: llama-3.3-70b-instruct

        - type: content_safety
          engine: nim
          parameters:
            base_url: "http://nim-content-safety:8000"
            model_name: llama-3.1-nemoguard-8b-content-safety

        - type: topic_control
          engine: nim
          parameters:
            base_url: "http://nim-topic-control:8000"
            model_name: llama-3.1-nemoguard-8b-topic-control

      rails:
        input:
          parallel: True
          flows:
            - content safety check input $$model=content_safety
            - topic safety check input $$model=topic_control
            - jailbreak detection model

        output:
          parallel: True
          flows:
            - content safety check output $$model=content_safety

        config:
          jailbreak_detection:
            nim_base_url: http://nim-jailbreak:8000
            nim_server_endpoint: /v1/security/nvidia/nemoguard-jailbreak-detect

  nvbuild_config:
    content: |
      models:
        - model_id: meta/llama-3.3-70b-instruct
          engine: nim
          model: meta/llama-3.3-70b-instruct
          base_url: https://integrate.api.nvidia.com/v1

        - model_id: nvidia/llama-3.1-nemoguard-8b-content-safety
          engine: nim
          model: nvidia/llama-3.1-nemoguard-8b-content-safety
          base_url: https://integrate.api.nvidia.com/v1

        - model_id: nvidia/llama-3.1-nemoguard-8b-topic-control
          engine: nim
          model: nvidia/llama-3.1-nemoguard-8b-topic-control
          base_url: https://integrate.api.nvidia.com/v1

  nvbuild_default_config:
    content: |
      models: []

  nvbuild_quickstart_config:
    content: |
      models:
        - type: main
          engine: nim
          model: meta/llama-3.3-70b-instruct

        - type: content_safety
          engine: nim
          model: nvidia/llama-3.1-nemoguard-8b-content-safety
          api_key_env_var: NIM_API_KEY

        - type: topic_control
          engine: nim
          model: nvidia/llama-3.1-nemoguard-8b-topic-control
          api_key_env_var: NIM_API_KEY

      rails:
        input:
          parallel: True
          flows:
            - content safety check input $$model=content_safety
            - topic safety check input $$model=topic_control
            - jailbreak detection model

        output:
          parallel: True
          flows:
            - content safety check output $$model=content_safety

      config:
        jailbreak_detection:
          nim_base_url: "https://ai.api.nvidia.com"
          nim_server_endpoint: "/v1/security/nvidia/nemoguard-jailbreak-detect"
          api_key: NIM_API_KEY


  quickstart_prompts:
    content: |
      prompts:

        - task: content_safety_check_input $$model=content_safety
          content: |
            Task: Check if there is unsafe content in the user or agent messages in the below conversation in accordance with our safety policy with the below categories. Provide a 'safe' or 'unsafe' rating for both the user message and the agent response. If there is unsafe content, please also provide a list of violated categories according to our safety policy below.

            <BEGIN UNSAFE CONTENT CATEGORIES>
            S1: Violence.
            S2: Sexual.
            S3: Criminal Planning/Confessions.
            S4: Guns and Illegal Weapons.
            S5: Controlled/Regulated Substances.
            S6: Suicide and Self Harm.
            S7: Sexual (minor).
            S8: Hate/Identity Hate.
            S9: PII/Privacy.
            S10: Harassment.
            S11: Threat.
            S12: Profanity.
            S13: Needs Caution.
            S14: Other.
            S15: Manipulation.
            S16: Fraud/Deception.
            S17: Malware.
            S18: High Risk Gov Decision Making.
            S19: Political/Misinformation/Conspiracy.
            S20: Copyright/Trademark/Plagiarism.
            S21: Unauthorized Advice.
            S22: Illegal Activity.
            S23: Immoral/Unethical.
            <END UNSAFE CONTENT CATEGORIES>

            <BEGIN CONVERSATION>

            user: {{ user_input }}

            <END CONVERSATION>

            Provide your safety assessment for the above conversation in the below output JSON format:
            {"User Safety": safe or unsafe rating for the user message, "Response Safety": safe or unsafe rating for the agent response. Omit if no agent response present. "Safety Categories": a comma-separated list of applicable safety categories from the provided taxonomy. Omit if all safe.}

            Do not include anything other than the output JSON in your response.
            Output JSON:
          output_parser: nemoguard_parse_prompt_safety
          max_tokens: 50

        - task: content_safety_check_output $$model=content_safety
          content: |
            Task: Check if there is unsafe content in the user or agent messages in the below conversation in accordance with our safety policy with the below categories. Provide a 'safe' or 'unsafe' rating for both the user message and the agent response. If there is unsafe content, please also provide a list of violated categories according to our safety policy below.

            <BEGIN UNSAFE CONTENT CATEGORIES>
            S1: Violence.
            S2: Sexual.
            S3: Criminal Planning/Confessions.
            S4: Guns and Illegal Weapons.
            S5: Controlled/Regulated Substances.
            S6: Suicide and Self Harm.
            S7: Sexual (minor).
            S8: Hate/Identity Hate.
            S9: PII/Privacy.
            S10: Harassment.
            S11: Threat.
            S12: Profanity.
            S13: Needs Caution.
            S14: Other.
            S15: Manipulation.
            S16: Fraud/Deception.
            S17: Malware.
            S18: High Risk Gov Decision Making.
            S19: Political/Misinformation/Conspiracy.
            S20: Copyright/Trademark/Plagiarism.
            S21: Unauthorized Advice.
            S22: Illegal Activity.
            S23: Immoral/Unethical.
            <END UNSAFE CONTENT CATEGORIES>

            <BEGIN CONVERSATION>

            user: {{ user_input }}

            response: agent: {{ bot_response }}

            <END CONVERSATION>

            Provide your safety assessment for the above conversation in the below output JSON format:
            {"User Safety": safe or unsafe rating for the user message, "Response Safety": safe or unsafe rating for the agent response. Omit if no agent response present. "Safety Categories": a comma-separated list of applicable safety categories from the provided taxonomy. Omit if all safe.}

            Do not include anything other than the output JSON in your response.
            Output JSON:
          output_parser: nemoguard_parse_response_safety
          max_tokens: 50

        - task: topic_safety_check_input $$model=topic_control
          content: |
            You are to act as a customer service agent, providing users with factual information in accordance to the knowledge base. Your role is to ensure that you respond only to relevant queries and adhere to the following guidelines

            Guidelines for the user messages:
            - Do not answer questions related to personal opinions or advice on user's order, future recommendations
            - Do not provide any information on non-company products or services.
            - Do not answer enquiries unrelated to the company policies.
            - Do not answer questions asking for personal details about the agent or its creators.
            - Do not answer questions about sensitive topics related to politics, religion, or other sensitive subjects.
            - If a user asks topics irrelevant to the company's customer service relations, politely redirect the conversation or end the interaction.
            - Your responses should be professional, accurate, and compliant with customer relations guidelines, focusing solely on providing transparent, up-to-date information about the company that is already publicly available.
            - allow user comments that are related to small talk and chit-chat.

services:
  guardrails:
    image: ${NEMO_MICROSERVICES_IMAGE_REGISTRY}/guardrails:${NEMO_MICROSERVICES_IMAGE_TAG}
    profiles: [guardrails, platform]
    # we don't currently have a cross platform build for guardrails
    platform: linux/amd64
    environment:
      - LOG_LEVEL=INFO
      - TELEMETRY_ENABLED=false
      - DB_URI="postgresql://nmp:nmp@postgres:5432/guardrails"
      - DEMO=true
      - CONFIG_STORE_PATH=/config-store
      - NIM_ENDPOINT_API_KEY
      - NIM_ENDPOINT_URL
      - NIM_API_KEY
      - NVIDIA_API_KEY
    ports:
      - 7331
    configs:
      # model configs
      - source: ${GUARDRAILS_CONFIG_TYPE:-nvbuild}_config
        target: /config-store/config.yaml
        gid: "1000"
        uid: "1000"

      # default configs
      - source: ${GUARDRAILS_CONFIG_TYPE:-nvbuild}_default_config
        target: /config-store/default/config.yaml
        gid: "1000"
        uid: "1000"

      # quickstart configs
      - source: ${GUARDRAILS_CONFIG_TYPE:-nvbuild}_quickstart_config
        target: /config-store/quickstart/config.yaml
        gid: "1000"
        uid: "1000"

      - source: quickstart_prompts
        target: /config-store/quickstart/prompts.yaml
        gid: "1000"
        uid: "1000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; assert urllib.request.urlopen('http://localhost:7331/v1/health').status == 200"]
    depends_on:
      guardrails-db-migration:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - nmp

  guardrails-db-migration:
    image: ${NEMO_MICROSERVICES_IMAGE_REGISTRY}/guardrails:${NEMO_MICROSERVICES_IMAGE_TAG}
    profiles: [guardrails, platform]
    # we don't currently have a cross platform build for guardrails
    platform: linux/amd64
    entrypoint: ["alembic", "upgrade", "head"]
    environment:
      POSTGRES_URI: "postgresql://nmp:nmp@postgres:5432/guardrails"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nmp

  ##############################
  # NIMS - disabled by default #
  ##############################

  # Base Model
  # https://build.nvidia.com/meta/llama-3_3-70b-instruct/deploy
  llama-3-3-70b-instruct:
    image: nvcr.io/nim/meta/llama-3.3-70b-instruct:latest
    profiles: [guardrails-nims, llama-3-3-70b-instruct]
    shm_size: 16gb
    ports:
      - "8000"
    environment:
      - NGC_API_KEY
      - NIM_SERVED_MODEL_NAME=llama-3.3-70b-instruct
      - NIM_CUSTOM_MODEL_NAME=llama-3.3-70b-instruct
    volumes:
      - nim_model_cache:/opt/nim/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    runtime: nvidia
    networks:
      - nmp

  # Topic control
  # https://build.nvidia.com/nvidia/llama-3_1-nemoguard-8b-topic-control
  # nvcr.io/nim/nvidia/llama-3.1-nemoguard-8b-topic-control:latest
  nim-topic-control:
    image: nvcr.io/nim/nvidia/llama-3.1-nemoguard-8b-topic-control:latest
    profiles: [guardrails-nims, nims-topic-control]
    shm_size: 16gb
    ports:
      - "8000"
    environment:
      - NGC_API_KEY
      - NIM_SERVED_MODEL_NAME=llama-3.1-nemoguard-8b-topic-control
      - NIM_CUSTOM_MODEL_NAME=llama-3.1-nemoguard-8b-topic-control
      - NIM_ENABLE_KV_CACHE_REUSE=1
    volumes:
      - nim_model_cache:/opt/nim/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"]
              capabilities: [gpu]
    runtime: nvidia
    networks:
      - nmp

  # Jailbreak
  # https://build.nvidia.com/nvidia/nemoguard-jailbreak-detect
  # nvcr.io/nim/nvidia/nemoguard-jailbreak-detect:1.0.0
  nim-jailbreak:
    image: nvcr.io/nim/nvidia/nemoguard-jailbreak-detect:latest
    profiles: [guardrails-nims, nims-jailbreak]
    shm_size: 16gb
    ports:
      - "8000"
    environment:
      - NGC_API_KEY
    volumes:
      - nim_model_cache:/opt/nim/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["2"]
              capabilities: [gpu]
    runtime: nvidia
    networks:
      - nmp

  # Content Safety
  # https://build.nvidia.com/nvidia/llama-3_1-nemoguard-8b-content-safety
  # nvcr.io/nim/nvidia/llama-3.1-nemoguard-8b-content-safety:latest
  nim-content-safety:
    image: nvcr.io/nim/nvidia/llama-3.1-nemoguard-8b-content-safety:latest
    profiles: [guardrails-nims, nims-content-safety]
    shm_size: 16gb
    ports:
      - "8000"
    environment:
      - NGC_API_KEY
      - NIM_SERVED_MODEL_NAME=llama-3.1-nemoguard-8b-content-safety
      - NIM_CUSTOM_MODEL_NAME=llama-3.1-nemoguard-8b-content-safety
      - NIM_ENABLE_KV_CACHE_REUSE=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["3"]
              capabilities: [gpu]
    runtime: nvidia
    networks:
      - nmp

volumes:
  nim_model_cache:
