version: 2.1

orbs:
  node: circleci/node@7.1.1
  python: circleci/python@3.2.0
  docker: circleci/docker@3.0.0

workflows:
  build-and-test:
    jobs:
      - node-test
      - python-test
      - docker-build

jobs:
  node-test:
    docker:
      - image: cimg/node:22.19.0-browsers
    steps:
      - checkout
      - node/install
      - run:
          name: Install dependencies
          command: |
            if [ -f pnpm-lock.yaml ]; then
              npm install -g pnpm
              pnpm install
            elif [ -f package-lock.json ]; then
              npm install
            elif [ -f yarn.lock ]; then
              npm install -g yarn
              yarn install
            else
              npm install
            fi
      - run:
          name: Run linting
          command: |
            if command -v pnpm &> /dev/null; then
              pnpm run lint || true
            else
              npm run lint || true
            fi
      - run:
          name: Run tests
          command: |
            if command -v pnpm &> /dev/null; then
              pnpm run test || true
            else
              npm run test || true
            fi
      - run:
          name: Build application
          command: |
            if command -v pnpm &> /dev/null; then
              pnpm run build || true
            else
              npm run build || true
            fi

  python-test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install dependencies
          command: |
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            elif [ -f pyproject.toml ]; then
              pip install .
            fi
      - run:
          name: Run linting
          command: flake8 src api || true
      - run:
          name: Run tests
          command: python -m pytest || true

  docker-build:
    executor: docker/docker
    steps:
      - checkout
      - docker/build:
          image: $CIRCLE_PROJECT_REPONAME
          tag: $CIRCLE_SHA1
