---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixelated-app
  namespace: pixelated
  labels:
    app: pixelated
    component: web
    environment: production
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: pixelated
      component: web
  template:
    metadata:
      labels:
        app: pixelated
        component: web
        environment: production
    spec:
      # Security Context - adapted for Civo
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001

      containers:
      - name: pixelated
        image: pixelatedempathy/pixelated-empathy:latest
        command: ["node", "./dist/server/entry.mjs"]
        ports:
        - containerPort: 4321
          name: http
          protocol: TCP
        
        # Resource limits adapted for Civo
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /
            port: 4321
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /
            port: 4321
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

        # Environment variables
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "4321"

---
apiVersion: v1
kind: Service
metadata:
  name: pixelated-service
  namespace: pixelated
  labels:
    app: pixelated
    component: web
spec:
  selector:
    app: pixelated
    component: web
  ports:
  - port: 80
    targetPort: 4321
    protocol: TCP
    name: http
  type: ClusterIP