---
apiVersion: v1
kind: Namespace
metadata:
  name: pixelated
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixelated
  namespace: pixelated
  labels:
    app: pixelated-app
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pixelated-app
  template:
    metadata:
      labels:
        app: pixelated-app
        version: v1.0.0
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: pixelated
          image: registry.gitlab.com/pixeldeck/pixelated@sha256:1691c565a3f08071ff8a0ad27af889ec4964d23fc035b2f30d2ae8ce9ec8b0e6
          ports:
            - containerPort: 4321
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "4321"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 4321
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 4321
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
            - name: secrets-volume
              mountPath: /app/secrets
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
            runAsUser: 10001
            runAsGroup: 10001
      volumes:
        - name: config-volume
          configMap:
            name: pixelated-config
        - name: secrets-volume
          secret:
            secretName: pixelated-secrets
      imagePullSecrets:
        - name: regcred
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: pixelated-service
  namespace: pixelated
  labels:
    app: pixelated-app
spec:
  selector:
    app: pixelated-app
  ports:
    - name: http
      port: 80
      targetPort: 4321
      protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pixelated-ingress
  namespace: pixelated
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: "caddy"
  tls:
    - hosts:
        - pixelatedempathy.com
        - www.pixelatedempathy.com
      secretName: pixelated-tls
  rules:
    - host: pixelatedempathy.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pixelated-service
                port:
                  number: 80
    - host: www.pixelatedempathy.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pixelated-service
                port:
                  number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pixelated-config
  namespace: pixelated
data:
  app.json: |
    {
      "name": "pixelated",
      "version": "1.0.0",
      "environment": "production",
      "features": {
        "ai_chat": true,
        "user_registration": true,
        "analytics": true
      }
    }
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pixelated-hpa-advanced
  namespace: pixelated
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pixelated
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
    - type: Pods
      pods:
        metric:
          name: http_requests_per_second
        target:
          type: AverageValue
          averageValue: "1000"
    - type: Object
      object:
        metric:
          name: requests-per-second
        describedObject:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          name: pixelated-ingress
        target:
          type: Value
          value: "10k"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
        - type: Pods
          value: 4
          periodSeconds: 60
      selectPolicy: Max
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pixelated-pdb
  namespace: pixelated
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: pixelated-app
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pixelated-allow-http
  namespace: pixelated
spec:
  podSelector:
    matchLabels:
      app: pixelated-app
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 4321
  egress:
    - {}
