---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pixelated-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - pixelatedempathy.com
      secretName: pixel-tls

  rules:
    - host: pixelatedempathy.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pixelated-service
                port:
                  number: 80
