apiVersion: v1
kind: Service
metadata:
  name: pixelated-service
  namespace: pixelated
  labels:
    app: pixelated-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4321
    protocol: TCP
    name: http
  selector:
    app: pixelated-app