apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pixelated-web-pdb
  namespace: pixelated-prod
  labels:
    app: pixelated
    component: web
    environment: production
spec:
  minAvailable: 2  # Ensure at least 2 pods are always available
  selector:
    matchLabels:
      app: pixelated
      component: web
      environment: production

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pixelated-db-pdb
  namespace: pixelated-prod
  labels:
    app: pixelated
    component: database
    environment: production
spec:
  minAvailable: 1  # Ensure database is always available
  selector:
    matchLabels:
      app: pixelated
      component: database

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pixelated-redis-pdb
  namespace: pixelated-prod
  labels:
    app: pixelated
    component: cache
    environment: production
spec:
  minAvailable: 1  # Ensure Redis is always available
  selector:
    matchLabels:
      app: pixelated
      component: redis

---
# Network Policies for security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pixelated-web-network-policy
  namespace: pixelated-prod
  labels:
    app: pixelated
    component: web
    environment: production
spec:
  podSelector:
    matchLabels:
      app: pixelated
      component: web
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow HTTP/HTTPS traffic from load balancer
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 3000
  # Allow traffic from other pixelated services
  - from:
    - podSelector:
        matchLabels:
          app: pixelated
    ports:
    - protocol: TCP
      port: 3000
  # Allow health checks from kube-system
  - from:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: TCP
      port: 3000
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
  # Allow traffic to pixelated services
  - to:
    - podSelector:
        matchLabels:
          app: pixelated
    ports:
    - protocol: TCP
      port: 5432  # PostgreSQL
    - protocol: TCP
      port: 6379  # Redis
    - protocol: TCP
      port: 5000  # AI Service
  # Allow HTTPS outbound (for external APIs)
  - to: []
    ports:
    - protocol: TCP
      port: 443
  # Allow HTTP outbound (for external services)
  - to: []
    ports:
    - protocol: TCP
      port: 80

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pixelated-db-network-policy
  namespace: pixelated-prod
  labels:
    app: pixelated
    component: database
    environment: production
spec:
  podSelector:
    matchLabels:
      app: pixelated
      component: database
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow traffic from pixelated web pods
  - from:
    - podSelector:
        matchLabels:
          app: pixelated
          component: web
    ports:
    - protocol: TCP
      port: 5432
  # Allow traffic from pixelated AI service
  - from:
    - podSelector:
        matchLabels:
          app: pixelated
          component: ai-service
    ports:
    - protocol: TCP
      port: 5432
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pixelated-redis-network-policy
  namespace: pixelated-prod
  labels:
    app: pixelated
    component: cache
    environment: production
spec:
  podSelector:
    matchLabels:
      app: pixelated
      component: redis
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow traffic from pixelated web pods
  - from:
    - podSelector:
        matchLabels:
          app: pixelated
          component: web
    ports:
    - protocol: TCP
      port: 6379
  # Allow traffic from pixelated AI service
  - from:
    - podSelector:
        matchLabels:
          app: pixelated
          component: ai-service
    ports:
    - protocol: TCP
      port: 6379
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53

---
# Resource Quota for the namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pixelated-prod-quota
  namespace: pixelated-prod
  labels:
    app: pixelated
    environment: production
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    pods: "50"
    services: "20"
    secrets: "20"
    configmaps: "20"

---
# Limit Range for pods
apiVersion: v1
kind: LimitRange
metadata:
  name: pixelated-prod-limits
  namespace: pixelated-prod
  labels:
    app: pixelated
    environment: production
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 2Gi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
