apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixelated-empathy
  namespace: default
  labels:
    app: pixelated-empathy
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pixelated-empathy
  template:
    metadata:
      labels:
        app: pixelated-empathy
        version: v1.0.0
    spec:
      containers:
      - name: pixelated-empathy
        image: pixelated-empathy:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: pixelated-secrets
              key: db-host
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pixelated-secrets
              key: db-password
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: pixelated-secrets
              key: redis-host
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: pixelated-secrets
              key: jwt-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: pixelated-config
      imagePullSecrets:
      - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: pixelated-empathy-service
  namespace: default
  labels:
    app: pixelated-empathy
spec:
  selector:
    app: pixelated-empathy
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pixelated-empathy-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - pixelated-empathy.com
    - www.pixelated-empathy.com
    secretName: pixelated-empathy-tls
  rules:
  - host: pixelated-empathy.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pixelated-empathy-service
            port:
              number: 80
  - host: www.pixelated-empathy.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pixelated-empathy-service
            port:
              number: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pixelated-config
  namespace: default
data:
  app.json: |
    {
      "name": "pixelated-empathy",
      "version": "1.0.0",
      "environment": "production",
      "features": {
        "ai_chat": true,
        "user_registration": true,
        "analytics": true
      }
    }

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pixelated-empathy-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pixelated-empathy
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
