from typing import Any

class AudioSegment:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @classmethod
    def from_file(cls, file: str, format: str = ..., **kwargs: Any) -> AudioSegment: ...
    @property
    def dBFS(self) -> float: ...
    def __add__(self, other: AudioSegment) -> AudioSegment: ...
    def __len__(self) -> int: ...
    def export(self, out_f: str = ..., format: str = ..., **kwargs: Any) -> Any: ...
