#!/bin/bash
# Manual download instructions for NeMo Microservices quickstart

echo "=========================================="
echo "NeMo Microservices Quickstart - Manual Download"
echo "=========================================="
echo ""
echo "The automated download failed because NGC requires authentication."
echo ""
echo "Please follow these steps to download manually:"
echo ""
echo "1. Visit the NGC catalog:"
echo "   https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/resources/nemo-microservices-quickstart"
echo ""
echo "2. Sign in with your NVIDIA account"
echo ""
echo "3. Download the latest version (or version 25.10)"
echo ""
echo "4. Upload to the remote server:"
echo "   scp nemo-microservices-quickstart_v25.10.zip vivi@212.2.244.60:~/nemo-microservices/"
echo ""
echo "5. SSH into the server and extract:"
echo "   ssh vivi@212.2.244.60"
echo "   cd ~/nemo-microservices"
echo "   unzip nemo-microservices-quickstart_v25.10.zip"
echo ""
echo "6. Continue with deployment:"
echo "   cd nemo-microservices-quickstart_v25.10"
echo "   export NEMO_MICROSERVICES_IMAGE_REGISTRY='nvcr.io/nvidia/nemo-microservices'"
echo "   export NEMO_MICROSERVICES_IMAGE_TAG='25.10'"
echo "   export NIM_API_KEY='your-api-key'"
echo "   echo \$NIM_API_KEY | docker login nvcr.io -u '\$oauthtoken' --password-stdin"
echo "   docker compose --profile data-designer up -d"
echo ""
echo "=========================================="

