apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pixelated-web-hpa
  namespace: pixelated-prod
  labels:
    app: pixelated
    component: web
    environment: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pixelated-app
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: 100  # Scale up if average RPS > 100
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pixelated-prometheus-rules
  namespace: pixelated-prod
  labels:
    app: pixelated
    component: monitoring
data:
  prometheus-rules.yml: |
    groups:
    - name: pixelated-web.rules
      rules:
      # High CPU usage alert
      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total{pod=~"pixelated-app-.*"}[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
          service: pixelated-web
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 5 minutes"

      # High memory usage alert
      - alert: HighMemoryUsage
        expr: container_memory_usage_bytes{pod=~"pixelated-app-.*"} / container_spec_memory_limit_bytes > 0.85
        for: 5m
        labels:
          severity: warning
          service: pixelated-web
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 85% for more than 5 minutes"

      # High error rate alert
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
          service: pixelated-web
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% for more than 5 minutes"

      # Slow response time alert
      - alert: SlowResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          service: pixelated-web
        annotations:
          summary: "Slow response time detected"
          description: "95th percentile response time is above 2 seconds"

      # Database connection issues
      - alert: DatabaseConnectionIssues
        expr: rate(postgres_connection_errors_total[5m]) > 5
        for: 2m
        labels:
          severity: critical
          service: database
        annotations:
          summary: "Database connection issues detected"
          description: "More than 5 database connection errors in 5 minutes"

      # Redis connection issues
      - alert: RedisConnectionIssues
        expr: redis_connected_clients < 5
        for: 2m
        labels:
          severity: critical
          service: redis
        annotations:
          summary: "Redis connection issues detected"
          description: "Redis has fewer than 5 connected clients"

      # Pod restart alert
      - alert: PodRestart
        expr: increase(kube_pod_container_status_restarts_total{pod=~"pixelated-app-.*"}[10m]) > 0
        for: 1m
        labels:
          severity: warning
          service: pixelated-web
        annotations:
          summary: "Pod restart detected"
          description: "A pod has restarted in the last 10 minutes"

      # Disk space alert
      - alert: LowDiskSpace
        expr: (1 - node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: infrastructure
        annotations:
          summary: "Low disk space detected"
          description: "Disk usage is above 85%"

    - name: pixelated-business.rules
      rules:
      # Bias detection accuracy alert
      - alert: LowBiasDetectionAccuracy
        expr: pixelated_bias_detection_accuracy < 0.95
        for: 15m
        labels:
          severity: warning
          service: bias-detection
        annotations:
          summary: "Low bias detection accuracy"
          description: "Bias detection accuracy has dropped below 95%"

      # High bias score alert
      - alert: HighBiasScoreDetected
        expr: pixelated_high_bias_score_total > 10
        for: 5m
        labels:
          severity: info
          service: bias-detection
        annotations:
          summary: "High bias scores detected"
          description: "More than 10 high bias scores detected in 5 minutes"

      # API rate limit alert
      - alert: APIRateLimitExceeded
        expr: rate(pixelated_api_rate_limit_exceeded_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "API rate limit exceeded"
          description: "API rate limit has been exceeded more than 10 times in 5 minutes"
