apiVersion: v2
name: pixelated-empathy
description: A Helm chart for Pixelated Empathy application
type: application
version: 1.0.1
appVersion: "1.0.0"
home: https://pixelatedempathy.com
sources:
  - https://github.com/pixelatedempathy/pixelated
maintainers:
  - name: Pixelated Empathy Team
    email: devops@pixelatedempathy.com
keywords:
  - ai
  - empathy
  - chat
  - mental-health
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: caddy-ingress-controller
    version: "1.0.0"
    repository: https://caddyserver.github.io/ingress/
    condition: ingress.enabled
