name: Copy Visual Regression Test Results

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Browser Compatibility Tests]
    types:
      - completed

# Set explicit permissions with least privilege
permissions: {}

jobs:
  copy-test-results:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Only job needs write access to push changes
      actions: read # To download artifacts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download test artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: browser-tests.yml
          name: browser-compatibility-report
          path: test-results-temp
          workflow_conclusion: ''
          if_no_artifact_found: warn

      - name: Create public test-results directory
        run: mkdir -p public/test-results

      - name: Copy test results to public directory
        run: |
          if [ -d "test-results-temp/test-results" ]; then
            cp -r test-results-temp/test-results/* public/test-results/
            echo "Copied test results to public/test-results/"
          else
            echo "No test results found to copy"
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

          git add public/test-results/

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update visual regression test results"
            git push
          fi
