name: Efficient Monitoring

on:
  schedule:
    # Run once daily instead of every 15 minutes
    - cron: '0 6 * * *'  # 6 AM UTC daily
  workflow_dispatch:

permissions: read-all

jobs:
  daily-health-summary:
    name: Daily Health Summary
    runs-on: ubuntu-latest
    
    steps:
      - name: Basic Health Check
        run: |
          echo "🏥 Running daily health summary..."
          
          # Just basic HTTP checks - no expensive setup
          BASE_URL="${{ vars.APP_URL || secrets.APP_URL }}"
          
          if [ -z "$BASE_URL" ]; then
            echo "::error::APP_URL not configured"
            exit 1
          fi
          
          # Check main site
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 "$BASE_URL")
          echo "Main site: HTTP $HTTP_STATUS"
          
          # Check health endpoint
          API_STATUS=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 "$BASE_URL/api/health/simple")
          echo "Health API: HTTP $API_STATUS"
          
          # Only fail if main site is completely down
          if [[ "$HTTP_STATUS" != "200" ]]; then
            echo "::error::Main site is down (HTTP $HTTP_STATUS)"
            exit 1
          fi
          
          echo "✅ Daily health check completed"

      - name: Notify Daily Status
        if: always()
        run: |
          STATUS="${{ job.status }}"
          if [ "$STATUS" = "success" ]; then
            echo "✅ Daily health check passed - all systems operational"
          else
            echo "❌ Daily health check failed - investigate immediately"
          fi
