# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy

permissions: read-all # Set restrictive default at workflow level

on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Set up environment variables
        run: |
          echo "Creating .env file for build"
          touch .env
          echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" >> .env
          echo "VITE_SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" >> .env
          echo "PUBLIC_SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" >> .env
          echo "NODE_TLS_REJECT_UNAUTHORIZED=0" >> .env

      - name: Deploy to Fly
        run: flyctl deploy --remote-only --build-arg DOCKER_BUILDKIT=1 --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg NODE_OPTIONS="--no-warnings" --build-secret SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          DOCKER_BUILDKIT: 1
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          VITE_SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          PUBLIC_SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NODE_TLS_REJECT_UNAUTHORIZED: '0'
          NODE_OPTIONS: --no-warnings
