name: GitHub Backup to Dropbox

permissions: read-all

on:
  schedule:
  - cron: 0 0 * * 0
  workflow_dispatch:


jobs:
  backup:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Create Dropbox folder (if missing)
      env:
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        DROPBOX_PATH: GitHub-Backup
      run: |
        # Create target Dropbox folder via API if it doesn't exist. This is idempotent.
        if [ -z "${DROPBOX_TOKEN}" ]; then
          echo "DROPBOX_TOKEN is not set. Skipping Dropbox folder creation step.";
          exit 0;
        fi

        CREATE_RESP=$(curl -s -o /dev/null -w "%{http_code}" \
          -X POST https://api.dropboxapi.com/2/files/create_folder_v2 \
          -H "Authorization: Bearer ${DROPBOX_TOKEN}" \
          -H "Content-Type: application/json" \
          --data "{\"path\": \"/${DROPBOX_PATH}\", \"autorename\": false}")

        if [ "$CREATE_RESP" = "409" ]; then
          echo "Dropbox folder /${DROPBOX_PATH} already exists.";
        elif [ "$CREATE_RESP" = "200" ] || [ "$CREATE_RESP" = "201" ]; then
          echo "Dropbox folder /${DROPBOX_PATH} created successfully.";
        else
          echo "Dropbox API responded with HTTP status $CREATE_RESP. Continuing - action may still succeed.";
        fi

    - name: Backup GitHub to Dropbox
      uses: chyroc/github2dropbox@v0.4.0
      with:
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
        ENABLE_REPO: true
        ENABLE_STAR: true
        ENABLE_FOLLOWER: true
        ENABLE_FOLLOWING: true
        ENABLE_GIST: true
        ENABLE_ISSUE: true
        ENABLE_ISSUE_COMMENT: true
        ENABLE_REPO_GIT: true
        DROPBOX_PATH: GitHub-Backup
