name: GitHub-Native Kubernetes Features

concurrency:
  group: github-k8s-native-features-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  packages: write
  issues: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      feature_type:
        description: "GitHub-native K8s feature to demonstrate"
        required: true
        type: choice
        options:
          - deployment-status
          - pr-integration
          - issue-automation
          - github-cli
          - marketplace-actions
          - security-advanced

env:
  NODE_VERSION: "24"
  PNPM_VERSION: "10.19.0"

jobs:
  deployment-status:
    name: GitHub-Native Deployment Status
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event.inputs.feature_type == 'deployment-status'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load GCP environment
        run: |
          # No .env parsing needed - use GitHub Secrets directly
          # GCP_PROJECT_ID, GKE_CLUSTER_NAME, GKE_ZONE are set via secrets in auth step
          echo "Using GitHub Secrets for GCP configuration"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GCP_SERVICE_ACCOUNT_KEY || secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.GCP_PROJECT_ID || secrets.GCP_PROJECT_ID }}
          universe: googleapis.com
          cleanup_credentials: true
          access_token_lifetime: 3600s
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform
          id_token_include_email: false

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER_NAME || secrets.GKE_CLUSTER_NAME }} \
            --zone ${{ env.GKE_ZONE || secrets.GKE_ZONE }} \
            --project ${{ env.GCP_PROJECT_ID || secrets.GCP_PROJECT_ID }}

      - name: Create GitHub-native deployment
        id: create_deployment
        uses: actions/github-script@v7
        with:
          script: |
            const cluster = process.env.GKE_CLUSTER_NAME || 'pixelcluster';
            const namespace = process.env.GKE_NAMESPACE || 'pixelated';
            const res = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              environment: 'production',
              description: `GKE Deployment: ${cluster} cluster`,
              auto_merge: false,
              required_contexts: [],
              payload: { cluster, namespace, strategy: 'rolling', github_native_features: true }
            });
            if (!res.data || !res.data.id) {
              throw new Error('GitHub API returned invalid deployment response');
            }
            console.log('✅ GitHub-native deployment created:', res.data.id);
            return res.data.id;

      - name: Update deployment status
        uses: actions/github-script@v7
        with:
          script: |
            const healthCheck = { pods_ready: '15/15', services_healthy: '5/5', deployments_stable: '3/3', cluster_health: 'healthy' };
            const deploymentId = '${{ steps.create_deployment.outputs.result }}';
            if (!deploymentId) {
              console.warn('No deployment_id available from previous step; skipping createDeploymentStatus');
              return;
            }
            
            if (isNaN(Number(deploymentId))) {
              throw new Error(`Invalid deployment_id: ${deploymentId}`);
            } else {
              await github.rest.repos.createDeploymentStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                deployment_id: Number(deploymentId),
                state: 'success',
                description: `K8s Health: ${healthCheck.pods_ready} pods ready`,
                environment_url: process.env.GKE_ENVIRONMENT_URL || 'http://35.243.226.27',
                log_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
              });
            }

  pr-integration:
    name: PR-Kubernetes Integration
    runs-on: ubuntu-latest
    if: github.event.inputs.feature_type == 'pr-integration'
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Load environment
        run: |
          # No .env parsing needed - use GitHub Secrets directly
          # GKE_ENVIRONMENT_URL is set via secrets in script step
          echo "Using GitHub Secrets for GKE environment URL"

      - name: Create PR deployment preview
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = process.env.GKE_ENVIRONMENT_URL || 'http://35.243.226.27';
            const cluster = process.env.GKE_CLUSTER_NAME || 'pixelcluster';
            const namespace = process.env.GKE_NAMESPACE || 'pixelated';
            const lines = [];
            lines.push('## 🚀 PR Preview Environment Ready');
            lines.push('');
            lines.push('**Kubernetes Integration Status:** ✅ Active');
            lines.push(`**Preview URL:** ${previewUrl}`);
            lines.push(`**Deployment Strategy:** Rolling Update`);
            lines.push('');
            lines.push('### 📊 K8s Health Status');
            lines.push(`- **Cluster:** ${cluster}`);
            lines.push(`- **Namespace:** ${namespace}`);
            lines.push(`- **Strategy:** Rolling deployment with health checks`);
            lines.push('');
            lines.push('### 🔧 GitHub-Native Features (GitLab Doesn\'t Have)');
            lines.push('- ✅ **PR Comments** - Automated deployment notifications');
            lines.push('- ✅ **Status Checks** - K8s health integration with PR status');
            lines.push('- ✅ **Deployment Reviews** - Required approvals before prod');
            lines.push('- ✅ **One-click Rollback** - Direct from PR interface');
            lines.push('- ✅ **Rich Markdown** - Better formatting than GitLab');
            lines.push('');
            lines.push('### 🎯 GitHub Advantages');
            lines.push('- **Native PR workflow** - Seamless GitHub integration');
            lines.push('- **Better commenting** - Rich markdown support');
            lines.push('- **Status API integration** - Real-time PR status updates');
            lines.push('- **Sophisticated approvals** - Advanced review workflows');
            const comment = lines.join('\n');
            if (context.issue && context.issue.number) {
              await github.rest.issues.createComment({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number, body: comment });
            } else {
              console.warn('No PR/issue context detected; skipping comment creation to avoid spam');
            }

  issue-automation:
    name: Issue-Kubernetes Automation
    runs-on: ubuntu-latest
    if: github.event.inputs.feature_type == 'issue-automation'
    steps:
      - name: Load environment
        run: |
          # No .env parsing needed - use GitHub Secrets directly
          # GKE_NAMESPACE and GKE_DEPLOYMENT_NAME are set via secrets in script step
          echo "Using GitHub Secrets for GKE namespace and deployment name"

      - name: Create K8s incident issue with GitHub-native features
        uses: actions/github-script@v7
        with:
          script: |
            const cluster = process.env.GKE_CLUSTER_NAME || 'pixelcluster';
            const namespace = process.env.GKE_NAMESPACE || 'pixelated';
            const deployment = process.env.GKE_DEPLOYMENT_NAME || 'pixelated';
            const issueBody = [
              '## 🚨 Kubernetes Deployment Issue',
              '',
              `**Cluster:** \`${cluster}\``,
              `**Namespace:** \`${namespace}\``,
              '**Environment:** Production',
              `**Reported by:** @${context.actor || github.actor || 'unknown'}`,
              '',
              '## 🔍 GitHub-Native Investigation Tools',
              '',
              '### Automated Diagnostics (GitLab doesn\'t have this)',
              '```bash',
              `kubectl get pods -n ${namespace}`,
              `kubectl describe deployment ${deployment}`,
              `kubectl logs -n ${namespace} -l app=pixelated --tail=100`,
              '```',
              '',
              '### GitHub Actions Integration',
              '- **Workflow Status:** Check Actions tab',
              '- **Deployment History:** View deployments',
              "- **One-click Rollback:** `gh workflow run gke-rollback.yml -f environment=production`",
              '',
              '### Next Steps',
              '1. Check cluster health using commands above',
              '2. Review deployment logs in Actions',
              '3. Consider rollback if health checks fail',
              '4. Monitor cost impact of any changes'
            ].join('\n');
            await github.rest.issues.create({ owner: context.repo.owner, repo: context.repo.repo, title: '🚨 Kubernetes Deployment Issue - Automated Detection', body: issueBody, labels: ['critical', 'kubernetes', 'deployment', 'automated'] });

  github-cli:
    name: GitHub CLI Kubernetes Integration
    runs-on: ubuntu-latest
    if: github.event.inputs.feature_type == 'github-cli'
    steps:
      - name: Demonstrate GitHub CLI K8s capabilities
        run: |
          echo "🔧 GitHub CLI provides SUPERIOR Kubernetes integration compared to GitLab"
          echo ""
          echo "## GitHub CLI K8s Commands (GitLab doesn't have equivalent):"
          echo ""
          echo "### Deployment Management:"
          echo "gh workflow run gke-deploy-enhanced.yml -f deployment_strategy=canary -f environment=production"
          echo "gh workflow run gke-rollback.yml -f environment=production"
          echo "gh workflow run gke-monitoring.yml -f check_type=comprehensive"
          echo ""
          echo "### Status Checking:"
          echo "gh api repos/${{ github.repository }}/deployments --jq '.[] | select(.environment==\"production\")'"
          echo "gh api repos/${{ github.repository }}/actions/runs --jq '.workflow_runs[] | select(.name==\"GKE Deployment Pipeline\")'"

  marketplace-actions:
    name: GitHub Marketplace K8s Actions
    runs-on: ubuntu-latest
    if: github.event.inputs.feature_type == 'marketplace-actions'
    steps:
      - name: Demonstrate marketplace ecosystem advantages
        run: |
          echo "🛒 GitHub Marketplace provides SUPERIOR K8s tooling vs GitLab"
          echo ""
          echo "## Available K8s Actions (GitLab doesn't have this ecosystem):"
          echo "- azure/k8s-deploy@v4"
          echo "- azure/k8s-set-context@v3"
          echo "- azure/k8s-create-secret@v4"

  security-advanced:
    name: Advanced GitHub-Native Security
    runs-on: ubuntu-latest
    if: github.event.inputs.feature_type == 'security-advanced'
    steps:
      - name: Demonstrate advanced security features
        run: |
          echo "🔒 GitHub provides SUPERIOR security integration vs GitLab"
          echo ""
          echo "## Advanced Security Features:"
          echo "- CodeQL analysis"
          echo "- Secret scanning"
          echo "- Dependency review"
