name: GKE Production Deploy

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Helm release name"
        required: true
        default: "pixelated"
      namespace:
        description: "Kubernetes namespace"
        required: true
        default: "production"
      image:
        description: "Container image repository"
        required: true
        default: "ghcr.io/pixelated/ai-service"
      tag:
        description: "Image tag (e.g., SHA)"
        required: true
      kubeconfig:
        description: "Base64-encoded kubeconfig (optional if using GKE auth steps)"
        required: false
        default: ""

jobs:
  production-deploy:
    name: Deploy to GKE (Production)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kubeconfig (if provided)
        if: inputs.kubeconfig != ''
        run: |
          echo "${{ inputs.kubeconfig }}" | base64 -d > $HOME/.kube/config

      - name: Deploy with Helm
        run: |
          bash scripts/deploy/production_deploy.sh \
            -r "${{ inputs.release }}" \
            -n "${{ inputs.namespace }}" \
            -i "${{ inputs.image }}" \
            -t "${{ inputs.tag }}" \
            --wait
