name: Multi-Pipeline Orchestrator

permissions:
  contents: read
  actions: write
  checks: write
  pull-requests: write
  security-events: write
  id-token: write

on:
  push:
    branches: [master, develop, feature/*, hotfix/*]
  pull_request:
    branches: [master, develop]
  workflow_dispatch:
    inputs:
      force_pipeline:
        description: 'Force specific pipeline execution'
        required: false
        default: 'auto'
        type: choice
        options:
          - auto
          - demo-pages
          - security-critical
          - infrastructure
          - hotfix
          - full-suite

env:
  NODE_VERSION: 22.16.0
  PYTHON_VERSION: 3.11
  PNPM_VERSION: 10.14.0
  ORCHESTRATOR_VERSION: 1.0.0

jobs:
  # Intelligent Change Analysis and Pipeline Routing
  change-analysis:
    name: Intelligent Change Analysis
    runs-on: ubuntu-latest
    outputs:
      pipeline_strategy: ${{ steps.analyze.outputs.pipeline_strategy }}
      risk_level: ${{ steps.analyze.outputs.risk_level }}
      test_strategy: ${{ steps.analyze.outputs.test_strategy }}
      deployment_strategy: ${{ steps.analyze.outputs.deployment_strategy }}
      affected_components: ${{ steps.analyze.outputs.affected_components }}
      complexity_score: ${{ steps.analyze.outputs.complexity_score }}
      security_impact: ${{ steps.analyze.outputs.security_impact }}
      demo_pages_changed: ${{ steps.analyze.outputs.demo_pages_changed }}
      infrastructure_changed: ${{ steps.analyze.outputs.infrastructure_changed }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Node.js for analysis
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable Corepack
        run: corepack enable

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Install analysis dependencies
        run: |
          pnpm add -D @octokit/rest simple-git glob fast-glob
          npm install -g @microsoft/rush-stack-compiler-4.7

      - name: Intelligent Change Analysis
        id: analyze
        run: |
          node -e "
          const fs = require('fs');
          const { execSync } = require('child_process');
          const path = require('path');
          
          // Get changed files
          let changedFiles = [];
          try {
            if (process.env.GITHUB_EVENT_NAME === 'pull_request') {
              const output = execSync('git diff --name-only origin/${{ github.base_ref }}...HEAD', { encoding: 'utf8' });
              changedFiles = output.trim().split('\n').filter(f => f);
            } else {
              const output = execSync('git diff --name-only HEAD~1 HEAD', { encoding: 'utf8' });
              changedFiles = output.trim().split('\n').filter(f => f);
            }
          } catch (e) {
            console.log('Using fallback file detection');
            changedFiles = ['src/pages/demo/bias-detection.astro']; // Fallback for initial runs
          }
          
          console.log('Changed files:', changedFiles);
          
          // Advanced change analysis
          const analysis = {
            demoPages: changedFiles.filter(f => f.includes('src/pages/demo/')),
            securityFiles: changedFiles.filter(f => 
              f.includes('security') || 
              f.includes('auth') || 
              f.includes('bias-detection') ||
              f.includes('fhe') ||
              f.includes('.env') ||
              f.includes('secrets')
            ),
            infrastructureFiles: changedFiles.filter(f => 
              f.includes('.github/workflows') ||
              f.includes('Dockerfile') ||
              f.includes('azure-pipelines') ||
              f.includes('infra/') ||
              f.includes('scripts/deploy')
            ),
            coreFiles: changedFiles.filter(f => 
              f.includes('src/lib/') ||
              f.includes('src/components/') ||
              f.includes('package.json') ||
              f.includes('astro.config')
            ),
            testFiles: changedFiles.filter(f => f.includes('test') || f.includes('spec')),
            configFiles: changedFiles.filter(f => 
              f.includes('config') ||
              f.includes('.yml') ||
              f.includes('.yaml') ||
              f.includes('.json')
            )
          };
          
          // Calculate complexity score (0-100)
          let complexityScore = 0;
          complexityScore += analysis.demoPages.length * 5;
          complexityScore += analysis.securityFiles.length * 15;
          complexityScore += analysis.infrastructureFiles.length * 20;
          complexityScore += analysis.coreFiles.length * 10;
          complexityScore += analysis.configFiles.length * 8;
          
          // Determine risk level
          let riskLevel = 'low';
          if (analysis.securityFiles.length > 0 || analysis.infrastructureFiles.length > 0) {
            riskLevel = 'high';
          } else if (analysis.coreFiles.length > 3 || complexityScore > 50) {
            riskLevel = 'medium';
          }
          
          // Determine pipeline strategy
          let pipelineStrategy = 'standard';
          if (process.env.FORCE_PIPELINE && process.env.FORCE_PIPELINE !== 'auto') {
            pipelineStrategy = process.env.FORCE_PIPELINE;
          } else if (analysis.demoPages.length > 0 && analysis.securityFiles.length === 0) {
            pipelineStrategy = 'demo-focused';
          } else if (analysis.securityFiles.length > 0) {
            pipelineStrategy = 'security-critical';
          } else if (analysis.infrastructureFiles.length > 0) {
            pipelineStrategy = 'infrastructure';
          } else if (riskLevel === 'high' || complexityScore > 70) {
            pipelineStrategy = 'full-suite';
          }
          
          // Determine test strategy
          let testStrategy = 'standard';
          if (riskLevel === 'high') {
            testStrategy = 'comprehensive';
          } else if (analysis.demoPages.length > 0) {
            testStrategy = 'demo-focused';
          } else if (complexityScore < 20) {
            testStrategy = 'minimal';
          }
          
          // Determine deployment strategy
          let deploymentStrategy = 'standard';
          if (riskLevel === 'high') {
            deploymentStrategy = 'canary';
          } else if (analysis.demoPages.length > 0) {
            deploymentStrategy = 'blue-green';
          }
          
          // Output results
          console.log('Analysis Results:');
          console.log('Pipeline Strategy:', pipelineStrategy);
          console.log('Risk Level:', riskLevel);
          console.log('Complexity Score:', complexityScore);
          console.log('Test Strategy:', testStrategy);
          console.log('Deployment Strategy:', deploymentStrategy);
          
          // Set GitHub outputs
          execSync(\`echo 'pipeline_strategy=\${pipelineStrategy}' >> \$GITHUB_OUTPUT\`);
          execSync(\`echo 'risk_level=\${riskLevel}' >> \$GITHUB_OUTPUT\`);
          execSync(\`echo 'test_strategy=\${testStrategy}' >> \$GITHUB_OUTPUT\`);
          execSync(\`echo 'deployment_strategy=\${deploymentStrategy}' >> \$GITHUB_OUTPUT\`);
          execSync(\`echo 'complexity_score=\${complexityScore}' >> \$GITHUB_OUTPUT\`);
          execSync(\`echo 'security_impact=\${analysis.securityFiles.length > 0}' >> \$GITHUB_OUTPUT\`);
          execSync(\`echo 'demo_pages_changed=\${analysis.demoPages.length > 0}' >> \$GITHUB_OUTPUT\`);
          execSync(\`echo 'infrastructure_changed=\${analysis.infrastructureFiles.length > 0}' >> \$GITHUB_OUTPUT\`);
          execSync(\`echo 'affected_components=' + JSON.stringify(Object.keys(analysis).filter(k => analysis[k].length > 0)) + ' >> \$GITHUB_OUTPUT\`);
          "
        env:
          FORCE_PIPELINE: ${{ github.event.inputs.force_pipeline }}

      - name: Generate Pipeline Execution Plan
        run: |
          echo "## 🚀 Pipeline Execution Plan" >> $GITHUB_STEP_SUMMARY
          echo "**Strategy:** ${{ steps.analyze.outputs.pipeline_strategy }}" >> $GITHUB_STEP_SUMMARY
          echo "**Risk Level:** ${{ steps.analyze.outputs.risk_level }}" >> $GITHUB_STEP_SUMMARY
          echo "**Complexity Score:** ${{ steps.analyze.outputs.complexity_score }}/100" >> $GITHUB_STEP_SUMMARY
          echo "**Test Strategy:** ${{ steps.analyze.outputs.test_strategy }}" >> $GITHUB_STEP_SUMMARY
          echo "**Deployment Strategy:** ${{ steps.analyze.outputs.deployment_strategy }}" >> $GITHUB_STEP_SUMMARY
          echo "**Affected Components:** ${{ steps.analyze.outputs.affected_components }}" >> $GITHUB_STEP_SUMMARY

  # Integrated Pipeline Execution
  execute-integrated-pipeline:
    name: Execute Integrated Pipeline
    needs: change-analysis
    uses: ./.github/workflows/pipeline-integration.yml
    with:
      pipeline_strategy: ${{ needs.change-analysis.outputs.pipeline_strategy }}
      risk_level: ${{ needs.change-analysis.outputs.risk_level }}
      complexity_score: ${{ needs.change-analysis.outputs.complexity_score }}
      deployment_strategy: ${{ needs.change-analysis.outputs.deployment_strategy }}
    secrets: inherit

  # Pipeline Coordination and Status Aggregation
  coordinate-pipelines:
    name: Pipeline Coordination
    runs-on: ubuntu-latest
    needs: [change-analysis, execute-integrated-pipeline]
    if: always()

    steps:
      - name: Aggregate Pipeline Results
        run: |
          echo "## 📊 Pipeline Execution Summary" >> $GITHUB_STEP_SUMMARY
          echo "| Component | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Change Analysis | ${{ needs.change-analysis.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Integrated Pipeline | ${{ needs.execute-integrated-pipeline.result }} |" >> $GITHUB_STEP_SUMMARY

      - name: Determine Overall Status
        id: overall-status
        run: |
          ANALYSIS_STATUS="${{ needs.change-analysis.result }}"
          PIPELINE_STATUS="${{ needs.execute-integrated-pipeline.result }}"

          OVERALL_STATUS="success"

          if [[ "$ANALYSIS_STATUS" == "failure" ]] || [[ "$PIPELINE_STATUS" == "failure" ]]; then
            OVERALL_STATUS="failure"
          elif [[ "$ANALYSIS_STATUS" == "cancelled" ]] || [[ "$PIPELINE_STATUS" == "cancelled" ]]; then
            OVERALL_STATUS="cancelled"
          fi

          echo "overall_status=$OVERALL_STATUS" >> $GITHUB_OUTPUT
          echo "## 🎯 Overall Orchestration Status: $OVERALL_STATUS" >> $GITHUB_STEP_SUMMARY

      - name: Post-Pipeline Actions
        if: steps.overall-status.outputs.overall_status == 'success'
        run: |
          echo "✅ Multi-pipeline orchestration completed successfully!"
          echo "🚀 Enterprise-grade CI/CD system executed flawlessly!"
          echo "📊 All quality gates, security checks, and compliance validations passed!"
