services:
  auditor:
    image: ${NEMO_MICROSERVICES_IMAGE_REGISTRY}/auditor:${NEMO_MICROSERVICES_IMAGE_TAG}
    profiles: [auditor, platform]
    environment:
      - POSTGRES_URI=postgresql://nmp:nmp@postgres:5432/auditor
      - CELERY_RESULT_BACKEND_URL=db+postgresql://nmp:nmp@postgres:5432/auditor
      - NIM_API_KEY
      - REST_API_KEY
      - OPENAI_API_KEY
      - OPENAICOMPATIBLE_API_KEY
      - NEMO_MICROSERVICES_AUDITOR_JOB_IMAGE=${NEMO_MICROSERVICES_IMAGE_REGISTRY}/auditor:${NEMO_MICROSERVICES_IMAGE_TAG}
    ports:
      - "5000"
    networks:
      - nmp
    configs:
      - source: platform_config
        target: /etc/nmp/config.yaml
        gid: "1000"
        uid: "1000"
        mode: 0444
    depends_on:
      postgres:
        condition: service_healthy
      datastore:
        condition: service_started
      nmp-core:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; assert urllib.request.urlopen('http://localhost:5000/health/ready').status == 200"]
