services:
  envoy-gateway:
    image: envoyproxy/envoy:v1.34-latest
    configs:
      - source: envoy_config
        target: /etc/envoy/envoy.yaml
        gid: "101"
        uid: "101"
        mode: 0444
    environment:
      - LOG_LEVEL=info
    ports:
      - "8080:8000"
    networks:
      - nmp
    ulimits:
      nofile:
        soft: 98304
        hard: 98304

configs:
  envoy_config:
    content: |
      node:
        id: gateway
        cluster: gateway

      admin:
        access_log_path: /dev/stdout
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 9901

      static_resources:
        listeners:
          - name: main
            address:
              socket_address:
                address: 0.0.0.0
                port_value: 8000
            filter_chains:
              - filters:
                  - name: envoy.filters.network.http_connection_manager
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                      stat_prefix: ingress_http
                      route_config:
                        name: local_route
                        virtual_hosts:
                          - name: backend
                            domains: ["*"]
                            routes:
                              # Infrastructure services
                              - match:
                                  prefix: "/v1/namespaces"
                                route:
                                  cluster: entity_store
                              - match:
                                  prefix: "/v1/projects"
                                route:
                                  cluster: entity_store
                              - match:
                                  prefix: "/v1/models"
                                route:
                                  cluster: entity_store
                              - match:
                                  prefix: "/v1/datasets"
                                route:
                                  cluster: entity_store
                              - match:
                                  prefix: "/v1/jobs"
                                route:
                                  cluster: nmp-core
                              - match:
                                  prefix: "/v2/inference/gateway/"
                                route:
                                  cluster: nmp-core
                              - match:
                                  prefix: "/v2/models"
                                route:
                                  cluster: nmp-core
                              - match:
                                  prefix: "/v2/inference"
                                route:
                                  cluster: nmp-core

                              # Functional services
                              - match:
                                  prefix: "/v1/data-designer/preview"
                                route:
                                  cluster: data_designer
                                  timeout: 600s
                              - match:
                                  prefix: "/v1/data-designer"
                                route:
                                  cluster: data_designer
                              - match:
                                  prefix: "/v1/guardrail"
                                route:
                                  cluster: guardrails
                                  timeout: 120s
                              - match:
                                  prefix: "/v1beta1/audit"
                                route:
                                  cluster: auditor
                              - match:
                                  prefix: "/v1/evaluation"
                                route:
                                  cluster: evaluator
                              - match:
                                  prefix: "/v2/evaluation"
                                route:
                                  cluster: evaluator
                              - match:
                                  prefix: "/v1/customization"
                                route:
                                  cluster: customizer
                              - match:
                                  prefix: "/v1beta1/safe-synthesizer"
                                route:
                                  cluster: safe-synthesizer
                              - match:
                                  prefix: "/v1/intake"
                                route:
                                  cluster: intake

                      http_filters:
                        - name: envoy.filters.http.router
                          typed_config:
                            "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        clusters:
          - name: nmp-core
            connect_timeout: 0.25s
            type: strict_dns
            lb_policy: round_robin
            load_assignment:
              cluster_name: nmp-core
              endpoints:
                - lb_endpoints:
                    - endpoint:
                        address:
                          socket_address:
                            address: nmp-core
                            port_value: 8000
          - name: data_designer
            type: strict_dns
            # lb_policy: round_robin
            load_assignment:
              cluster_name: data_designer
              endpoints:
                - lb_endpoints:
                    - endpoint:
                        address:
                          socket_address:
                            address: data-designer
                            port_value: 8000
          - name: guardrails
            type: strict_dns
            load_assignment:
              cluster_name: guardrails
              endpoints:
                - lb_endpoints:
                    - endpoint:
                        address:
                          socket_address:
                            address: guardrails
                            port_value: 7331
          - name: auditor
            type: strict_dns
            load_assignment:
              cluster_name: auditor
              endpoints:
                - lb_endpoints:
                    - endpoint:
                        address:
                          socket_address:
                            address: auditor
                            port_value: 5000
          - name: evaluator
            type: strict_dns
            load_assignment:
              cluster_name: evaluator
              endpoints:
                - lb_endpoints:
                    - endpoint:
                        address:
                          socket_address:
                            address: evaluator
                            port_value: 7331
          - name: entity_store
            type: strict_dns
            load_assignment:
              cluster_name: entity_store
              endpoints:
                - lb_endpoints:
                    - endpoint:
                        address:
                          socket_address:
                            address: entity-store
                            port_value: 8000
          - name: customizer
            type: strict_dns
            load_assignment:
              cluster_name: customizer
              endpoints:
                - lb_endpoints:
                    - endpoint:
                        address:
                          socket_address:
                            address: customizer
                            port_value: 8001

          - name: safe-synthesizer
            type: strict_dns
            load_assignment:
              cluster_name: safe-synthesizer
              endpoints:
                - lb_endpoints:
                    - endpoint:
                        address:
                          socket_address:
                            address: safe-synthesizer
                            port_value: 8000
          - name: intake
            type: strict_dns
            load_assignment:
              cluster_name: intake
              endpoints:
                - lb_endpoints:
                    - endpoint:
                        address:
                          socket_address:
                            address: intake
                            port_value: 8000
          - name: models
            type: strict_dns
            load_assignment:
              cluster_name: models
              endpoints:
                - lb_endpoints:
                    - endpoint:
                        address:
                          socket_address:
                            address: models-api
                            port_value: 8000
          - name: inference_gateway
            type: strict_dns
            load_assignment:
              cluster_name: inference_gateway
              endpoints:
                - lb_endpoints:
                    - endpoint:
                        address:
                          socket_address:
                            address: inference-gateway
                            port_value: 8000
