services:
  intake:
    image: ${NEMO_MICROSERVICES_IMAGE_REGISTRY}/intake:${NEMO_MICROSERVICES_IMAGE_TAG}
    profiles: [intake, platform]
    ports:
      - "8000"
    networks:
      - nmp
    environment:
      POSTGRES_URI: postgresql://nmp:nmp@postgres:5432/intake
      DATASTORE_URL: http://datastore:3000
      ENTITY_STORE_URL: http://entity-store:8000
    depends_on:
      postgres:
        condition: service_healthy
      intake-postgres-db-migration:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; assert urllib.request.urlopen('http://localhost:8000/health').status == 200"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 20s

  intake-postgres-db-migration:
    image: ${NEMO_MICROSERVICES_IMAGE_REGISTRY}/intake:${NEMO_MICROSERVICES_IMAGE_TAG}
    profiles: [intake, platform]
    working_dir: /app/services/intake
    environment:
      POSTGRES_URI: postgresql://nmp:nmp@postgres:5432/intake
    entrypoint: ["/app/.venv/bin/alembic"]
    command: ["upgrade", "head"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nmp

